development:
    dialect: postgres
    datasource: postgres://forna_user:12345@localhost:5432/forna
    dir: migrations
test:
    dialect: postgres
    datasource: postgres://forna_user:12345@localhost:5433/forna
    dir: migrations    