version: '3.6'

volumes:
  forna_data:
    driver: local

services:
  forna_postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: forna_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: forna
    volumes:
      - forna_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    environment:
      CONFIG_PATH: configuration-dev.json
    ports:
      - 10046:10046
    depends_on:
      - forna_postgresdb
    links:
      - forna_postgresdb